##################################################################################
#
# PHP Lockpick
# Helps accessing protected/private members/consts of foreign objects
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright 2014-2026 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/php-lockpick
#
##################################################################################

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
        args: [ '--maxkb=1555550' ]
      # This hook checks yaml files for parseable syntax
      - id: check-yaml
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensures that (non-binary) executables have a shebang.
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Prevent addition of new git submodules
      - id: forbid-new-submodules
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
        args: [ '--fix=no' ]

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
      # Runs PHPStan analyser
      - id: php-stan
        files: \.(php)$
      # Runs PHP CodeSniffer on changed files only
      - id: php-cs
        files: \.(php)$

  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0  # Use the ref you want to point at
    hooks:
    - id: mdformat
      # Optionally add plugins
      additional_dependencies:
      - mdformat-gfm
      - mdformat-black
      - mdformat-frontmatter

  # Markdown linting with markdownlint-cli
  # https://github.com/igorshubovych/markdownlint-cli
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.yaml"]

  # https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the ref you want to point at
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args: [ '--autofix', '--no-sort-keys' ]
