##################################################################################
#
# PHP Lockpick
# Helps accessing protected/private members/consts of foreign objects
#
# @author    Marcin Orlowski <mail (#) marcinOrlowski (.) com>
# @copyright 2014-2026 Marcin Orlowski
# @license   http://www.opensource.org/licenses/mit-license.php MIT
# @link      https://github.com/MarcinOrlowski/php-lockpick
#
##################################################################################

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Prevent giant files from being committed
      - id: check-added-large-files
        args: [ '--maxkb=1555550' ]
      # This hook checks yaml files for parseable syntax
      - id: check-yaml
      # Check for files that would conflict in case-insensitive filesystems
      - id: check-case-conflict
      # Ensures that (non-binary) executables have a shebang.
      - id: check-executables-have-shebangs
      # Check for files that contain merge conflict strings
      - id: check-merge-conflict
      # Prevent addition of new git submodules
      - id: forbid-new-submodules
      # Replaces or checks mixed line ending
      - id: mixed-line-ending
        args: [ '--fix=no' ]

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      # Non-executable shell script filename ends in .sh
      - id: script-must-have-extension

  - repo: https://github.com/MarcinOrlowski/pre-commit-hooks
    rev: 1.3.1
    hooks:
      # This hook trims trailing whitespace.
      - id: trailing-whitespaces
        exclude_types: ['xml','png','jpeg','svg']
        args: [ '--markdown-linebreak-ext=md', '--fix=yes' ]
      # Ensures that a file is either empty, or ends with one newline
      - id: end-of-file
        exclude_types: ['xml','png','jpeg','svg']
        args: [ '--fix=yes' ]

  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
    # Runs PHPStan analyser
    - id: php-stan
      files: \.(php)$
